# Generated by Django 4.0.3 on 2025-07-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
