# Generated by Django 4.0.3 on 2025-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0003_alter_groups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
