# Generated by Django 4.0.3 on 2025-07-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0004_groups_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='status',
        ),
    ]
