# Generated by Django 4.0.3 on 2025-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_remove_groups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='education',
            field=models.CharField(default='Not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='members',
            name='father',
            field=models.CharField(default='Not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='members',
            name='grandma',
            field=models.CharField(default='Not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='members',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='mother',
            field=models.CharField(default='Not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='members',
            name='thaivazhi',
            field=models.CharField(default='Not specified', max_length=250),
        ),
    ]
