# Generated by Django 4.0.3 on 2025-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0006_members_education_members_father_members_grandma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
