# Generated by Django 4.0.3 on 2025-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0007_alter_members_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='education',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='members',
            name='father',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='members',
            name='grandma',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='members',
            name='mother',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='members',
            name='thaivazhi',
            field=models.CharField(max_length=250),
        ),
    ]
